version: "3.9"

services:
  db:
    image: postgres:16
    container_name: users_db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./devops/init:/docker-entrypoint-initdb.d

  profile-service:
    build: ./users/profile-service
    container_name: profile-service
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  roles-service:
    build: ./users/roles-service
    container_name: roles-service
    depends_on:
      - db
    env_file:
      - ./users/roles-service/.env
    ports:
      - "8001:8001"
    command: >
      sh -c "sleep 5 && uvicorn app.main:app --host 0.0.0.0 --port 8001"

volumes:
  db_data:
