version: '3.9'

services:
  db:
    image: postgres:16
    container_name: profile-db
    environment:
      POSTGRES_USER: profile_user
      POSTGRES_PASSWORD: profile_pass
      POSTGRES_DB: profile_db
    ports:
      - "5433:5432"
    volumes:
      - profile_data:/var/lib/postgresql/data

  profile-service:
    build: .
    container_name: profile-service
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://profile_user:profile_pass@db:5432/profile_db

volumes:
  profile_data:
