version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: login_user
      POSTGRES_PASSWORD: login_pass
      POSTGRES_DB: login_db
    ports:
      - "5435:5432"
    volumes:
      - login-db-data:/var/lib/postgresql/data

  login-service:
    build: .
    ports:
      - "5003:5003"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://login_user:login_pass@db:5432/login_db

volumes:
  login-db-data:
