name: CI PROD - Deploy All Microservices

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Profile Service
        run: |
          docker build -t maxtarx969/profile-service:latest users/profile-service
          docker push maxtarx969/profile-service:latest

      - name: Build & Push Roles Service
        run: |
          docker build -t maxtarx969/roles-service:latest users/roles-service
          docker push maxtarx969/roles-service:latest

      - name: Build & Push Login Service
        run: |
          docker build -t maxtarx969/login-service:latest users/login-service
          docker push maxtarx969/login-service:latest

      - name: Build & Push Registration Service
        run: |
          docker build -t maxtarx969/registration-service:latest users/registration-service
          docker push maxtarx969/registration-service:latest
