name: CI/CD - Producción

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build y Deploy a DockerHub
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build y Push del profile-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/profile-service:latest users/profile-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/profile-service:latest
    
    - name: Build y Push del roles-service
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/roles-service:latest users/roles-service
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/roles-service:latest