name: CI QA

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "qa" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code (optional)
      run: |
        echo "Lint check or formatter here, if needed"

    - name: Build Docker image
      run: |
        docker build -t esmaigua/profile-service:qa .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to Docker Hub
      run: docker push esmaigua/profile-service:qa
