name: QA Pipeline

on:
  push:
    branches:
      - qa

jobs:
  test:
    name: Lint and Tests - profile & roles services
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: users_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r users/profile-service/requirements.txt
        pip install -r users/roles-service/requirements.txt
        pip install flake8

    - name: Create required tables
      run: |
        sudo apt-get update && sudo apt-get install -y postgresql-client
        echo "Creating profiles table..."
        psql -h localhost -U postgres -d users_db -c "
        CREATE TABLE IF NOT EXISTS profiles (
          id SERIAL PRIMARY KEY,
          user_id UUID NOT NULL,
          full_name VARCHAR(255),
          birth_date DATE,
          phone_number VARCHAR(20),
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );"

        echo "Creating roles table..."
        psql -h localhost -U postgres -d users_db -c "
        CREATE TABLE IF NOT EXISTS roles (
          id SERIAL PRIMARY KEY,
          role_name VARCHAR(50) NOT NULL,
          description TEXT
        );"
      env:
        PGPASSWORD: postgres

    - name: Run Flake8 (profile-service)
      working-directory: users/profile-service
      run: flake8 app/

    - name: Run Flake8 (roles-service)
      working-directory: users/roles-service
      run: flake8 app/

    - name: Run Pytest (profile-service)
      env:
        POSTGRES_DB: users_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        PYTHONPATH: ${{ github.workspace }}/users/profile-service
      run: |
        pytest users/profile-service/test

    - name: Run Pytest (roles-service)
      env:
        POSTGRES_DB: users_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        PYTHONPATH: ${{ github.workspace }}/users/roles-service
      run: |
        pytest users/roles-service/test
