name: QA Pipeline

on:
  push:
    branches:
      - qa

jobs:
  test:
    name: Lint y Pruebas en profile-service
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      working-directory: users/profile-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Flake8
      working-directory: users/profile-service
      run: flake8 app/

    - name: Ejecutar Tests
      working-directory: users/profile-service
      run: |
        pip install pytest
        pytest test/
