name: CI QA - Profile Service

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'users/profile-service/**'
  pull_request:
    branches: [ "qa" ]
    paths:
      - 'users/profile-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r users/profile-service/requirements.txt

      - name: Build Docker image
        run: docker build -t profile-service:qa users/profile-service
