<<<<<<< HEAD
name: CI-QA Login Service

on:
  push:
    branches: ["develop"]
    paths:
      - "users/login-service/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/distributed-clothing-plataform-login-service:qa ./users/login-service
          docker push ${{ secrets.DOCKER_USERNAME }}/distributed-clothing-plataform-login-service:qa
=======
name: CI QA - Roles Service

on:
  push:
    branches: [ "qa" ]
  pull_request:
    branches: [ "qa" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r users/login-service/requirements.txt

      - name: Build Docker image
        run: docker build -t login-service:qa users/login-service
>>>>>>> qa
