name: QA Pipeline

on:
  push:
    branches:
      - qa

jobs:
  test:
    name: Lint y Pruebas en profile-service
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: users_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      working-directory: users/profile-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Ejecutar Flake8
      working-directory: users/profile-service
      run: flake8 app/

    - name: Ejecutar Tests
      env:
        POSTGRES_DB: users_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        PYTHONPATH: ${{ github.workspace }}/users/profile-service
      run: |
        pytest users/profile-service/test
